### ISSUE TITLE
Commande Python

### ISSUE THREAD

**Issue by ECHOPAIN** [julienMeinas/PFE-Identification-rapide-d-ADN-duplique-dans-des-leucemies#17]
Voici la commande python que j'utilise pour lancer le script
python3 transformation.py -k 15 -t 0.3 ../../PFE-Identification-rapide-d-ADN-duplique-dans-des-leucemies/Project/Data/FLT3.fa ../../ressources/P6.fastq.gz > transform.txt

**Comment by mikael-s** [comment]
Quel message d'erreur/sortie as-tu avec cette commande ?

**Comment by ECHOPAIN** [comment]
je n'ai pas de message d'erreur et je pense que le programme s'exécute, seulement la commande ne se termine jamais et mon ordinateur devient de plus en plus lent.
